version: '3.4'

services:
  php:
    build:
      context: .
      target: php
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: .
      target: nginx
    depends_on:
      - php
    ports:
      - "80:80"

  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phptools:
    build:
      context: .
      target: phptools
