version: '3.4'

services:
  php:
    build:
      context: .
      target: php
    volumes:
      - ./:/srv/paygreen:rw,cached

  phpstan:
    build:
      context: .
      target: phpstan
    volumes:
      - ./:/srv/paygreen:rw,cached
