name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Composer
        uses: php-actions/composer@v5
        with:
          version: 1
          php_version: 7.4
          php_extensions: zip

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          version: 5.7
          php_version: 5.6
          configuration: phpunit.xml.dist
          args: --coverage-text

  behat:
    runs-on: ubuntu-latest
    environment: SANDBOX

    steps:
      - uses: actions/checkout@v2
      - name: Docker up
        env:
          SHOP_ID: "sh_eab202657e6f47b9b885c8448c4f1604"
          SECRET_KEY: "sk_9d316b106af84d24932eac6cc30c0efa"
          PUBLIC_KEY: "pk_d53790058c214eb6abbf9ddbc3805abe"
          BANK_CARD_PAN: "4970105191919435"
          BANK_CARD_CVV: "123"
          BANK_CARD_EXP: "0624"
          ENVIRONMENT: SANDBOX

        run: |
          docker-compose -f docker-compose.ci.yml up -d

      - name: Run behat tests through docker
        run: |
          docker-compose -f docker-compose.ci.yml exec -T php composer test:behat

      - name: Down containers to stop the video
        if: always()
        run: |
          docker-compose -f docker-compose.ci.yml down --remove-orphans

      - name: Archive videos results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: videos
          retention-days: 2
